services:
  - type: web
    name: code-togeather-server
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 3000
    healthCheckPath: /
